[package]
name = "mismem"
version = "0.1.0"
edition = "2018"

[dependencies]
tui = "0.19"
crossterm = "0.25"

[dependencies.windows]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging"
]